openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
servers:
  - url: http://127.0.0.1:5000
paths:
  /queue:
    post:
      summary: Create a pet
      operationId: createPets
      tags:
        - queue
      responses:
        '200':
          description: A paged array of pets
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Queue"
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Queue:
      type: object
      required:
        - dr_name
        - patient_name
        - patient_mobile_number
        - date
      properties:
        dr_name:
          type: string
        patient_name:
          type: string
        patient_mobile_number:
          type: string
        date:
          type: string
        tag:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
